# Generated by Django 3.0.2 on 2020-02-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0002_auto_20200201_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerChecker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0, unique=True)),
                ('answer', models.CharField(max_length=255)),
            ],
        ),
    ]
