# Generated by Django 3.0.4 on 2020-03-30 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0004_score_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='updated_at',
        ),
    ]
