# Generated by Django 3.0.4 on 2020-04-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0007_auto_20200419_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='ban',
            field=models.BooleanField(default=False),
        ),
    ]
